version: '3'

services:
  app_dev:
    env_file: 
      - ./.env
    image: kelwynoliveira/goexpert-deploy-with-cloud-run
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"